### PR TITLE
Bugfix (minor)

### PR DESCRIPTION
**Pull request by quotuva**

### CODE REVIEW

**Comment by timor** [comment]
If you don't mind me asking, what bug is being fixed by this?

**Comment by quotuva** [comment]
There's no `case` in Elisp. I think you might've meant `cond`? The original code raises an error there.

(Sorry for the lack of explanation earlier!)

**Comment by timor** [comment]
I see! Then the existing code is probably relying on having `case`  alias to what is now required to be `cl-case`. Thanks for noticing.

**Comment by quotuva** [comment]
I've been using this without any problems.

**Pull request merged**
